spring:
  datasource:
    url: jdbc:mariadb://dev.clvqx5zywpsr.ap-northeast-2.rds.amazonaws.com/dev
    username: guava
    password: mango00#

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

logging:
  path: ./logs
  config: classpath:logback-spring.xml